- name: Deploy Docker
  hosts: docker
  remote_user: aecid
  become: true
  roles:
    - role: wazuh_agent
      vars:
        wazuh_manager: 192.168.100.130
        wazuh_localfiles:
          - log_format: apache2
            location: /var/log/apache2/access.log
          - log_format: json
            location: /var/log/suricata/eve.json
