roles:
  - src: https://github.com/ait-cs-IaaS/ansible-manage_unattended_upgrades.git
    version: v1.0.0
    name: manage_unattended_upgrades
  - src: https://github.com/ait-testbed/atb-ansible-kafka.git
    version: v1.0.2
    name: kafka
  - src: https://github.com/ait-testbed/atb-ansible-hostname.git
    version: v1.0.0
    name: hostname
  - src: https://github.com/ait-testbed/atb-ansible-aeciduser.git
    version: v1.0.0
    name: aeciduser
  - src: https://github.com/ait-testbed/atb-ansible-aecidtools.git
    version: v1.0.0
    name: aecidtools
