- name: Install Fileshare Host
  hosts: all
  remote_user: debian
  become: true
  tasks:
    - name: Allow password login
      ansible.builtin.copy:
        dest: /etc/ssh/sshd_config.d/password.conf
        content: 'PasswordAuthentication yes'
  roles:
          - role: puppetclient
          - role: hostname
            vars:
                  hostname: linuxshare
                  hostname_ip: 192.168.100.23
                  hostname_fqdn: linuxshare.aecid-testbed.local
          - role: aeciduser
            vars:
                  # pass: aecid
                  aeciduser_pass: "$6$9AqxTPJqYsFXwgPN$xAC4y1Vndk00EaBCuFcJC37BYDYYVAgt9SHymg15KSdKddZnwG.SsQaJvHarH4DYQj3tuboeLa4G5EfL7itcC0"
          - role: aecidtools
            vars:
                  aecidtools_user: "aecid"
          - role: manage_unattended_upgrades
          - role: auditd
          - role: weaklinuxuser
          - role: disableresolved
          - role: healthcheck
            vars:
              healthcheck_wrapper_path: "/media/health"
              healthcheck_wrapper_mode: "0777"
              healthcheck_server: 192.168.100.23
          - role: nfsserver
            vars:
              nfsserver_shares:
                - /media/health      172.17.100.122(rw,sync,no_subtree_check)
                - /media/data        172.17.100.122(rw,sync,no_subtree_check)
          - role: zippeddata
            vars:
              zippeddata_data:
                - url: https://zenodo.org/records/7477560/files/Annotations.zip?download=1
                  path: /media/data
                - url: https://zenodo.org/records/7477560/files/Images.zip?download=1
                  path: /media/data
          - role: customdpkg
          - role: rootkeys
          - role: acct
          - role: ftploginjob
          - role: collectd
