- name: Install Attacker Host
  hosts: attacker
  become: true
  vars:
    attacker_user: aecid
    attacker_ip: 192.42.1.174
  handlers:
    - name: restart dnsmasq
      ansible.builtin.service:
        name: dnsmasq
        state: restarted
      delegate_to: inetdns

    - name: restart msfrpcd
      ansible.builtin.service:
        name: msfrpcd
        state: restarted

  tasks:
    - name: get user home directory
      ansible.builtin.shell: >
             getent passwd {{ attacker_user }}  | awk -F: '{ print $6 }'
      changed_when: false
      register: user_home
      tags:
        - playbooks

    - name: Install dependencies
      ansible.builtin.apt:
        pkg:
          - xz-utils
          - coreutils
      tags:
        - playbooks


    - name: Configure public DNS
      ansible.builtin.copy:
        content: "address=/facebock.com/{{ attacker_ip }}\n"
        owner: root
        dest: /etc/dnsmasq.d/attacker.conf
      delegate_to: inetdns
      notify: restart dnsmasq
      tags:
        - playbooks