- name: Deploy Repo
  hosts: linuxshare
  remote_user: aecid
  become: true
  roles:
    - role: healthcheck
      vars:
        healthcheck_wrapper_path: "/media/health"
        healthcheck_wrapper_mode: "0777"
        healthcheck_server: 192.168.100.23
