  - src: https://github.com/ait-cs-IaaS/ansible-mate-desktop.git
    version: v1.2.1
    name: mate-desktop
  - src: https://github.com/ait-testbed/atb-ansible-novnc.git
    version: v1.0.0
    name: novnc
  - src: https://github.com/ait-testbed/atb-ansible-rustdesk.git
    version: main
    name: rustdesk


    