- name: Upgrade Attacker Host
  hosts: attacker
  become: true
  vars:
    attacker_user: aecid
    attacker_ip: 192.42.1.174
    ansible_ssh_private_key_file: ~/.ssh/testbed
  roles:
    - role: rustdesk
      vars:
        install_server: true
        install_client: true