- name: Install Attacker Host
  become: true
  hosts: attacker
  roles:
    - role: attackmate
      vars:
        attackmate_sliverfix: True
        attackmate_version: development
        attackmate_msf_server: localhost
        attackmate_msf_passwd: hackerman
