- name: Install Attacker Host
  hosts: attacker
  become: true
  vars:
    attacker_user: aecid
  roles:
    - role: disableresolved
      vars:
            disableresolved_nameservers:
                    - 192.42.2.2
                    - 8.8.8.8
