roles:
  - src: https://github.com/ait-cs-IaaS/ansible-manage_unattended_upgrades.git
    version: v1.0.0
    name: manage_unattended_upgrades
  - src: https://github.com/ait-cs-IaaS/ansible-auditd.git
    version: v1.1
    name: auditd
  - src: https://github.com/ait-testbed/atb-ansible-aeciduser.git
    version: v1.0.0
    name: aeciduser
  - src: https://github.com/ait-testbed/atb-ansible-aecidtools.git
    version: v1.1.0
    name: aecidtools
  - src: https://github.com/ait-testbed/atb-ansible-wazuh_manager.git
    version: v0.9.0
    name: wazuh_manager
