---
- hosts: all
  become: true
  vars:
    suricata_interface: [ens3]
    suricata_pcap_log: False
  roles:
    - role: aeciduser
      vars:
            # pass: aecid
            aeciduser_pass: "$6$9AqxTPJqYsFXwgPN$xAC4y1Vndk00EaBCuFcJC37BYDYYVAgt9SHymg15KSdKddZnwG.SsQaJvHarH4DYQj3tuboeLa4G5EfL7itcC0"
    - role: suricata
    - role: auditd
    - role: dnsmasq
      vars:
        dnsmasq_systemd_resolved_disable: true
        dnsmasq_config:
              - { name: "logging",  content: "log-queries" }
              - { name: "host-video",  content: "host-record=video.aecid-testbed.com,192.42.0.254" }
              - { name: "host-firewall",  content: "host-record=fw.aecid-testbed.com,192.42.0.254" }
              - { name: "host-domain",  content: "host-record=aecid-testbed.com,192.42.0.254" }
              - { name: "auth-zone",  content: "auth-zone=aecid-testbed.com,192.42.0.254" }
              - { name: "auth-server",  content: "auth-server=192.42.0.233,,ens3" }
              - { name: "domain",  content: "domain=aecid-testbed.com" }
              - { name: "local-domain",  content: "local=/aecid-testbed.com/192.42.0.254" }
    - role: filebeat
      vars:
        filebeat_service_enabled: false
        filebeat_output_logstash_enabled: false
        filebeat_output_kafka_enabled: true
        filebeat_output_kafka_hosts:
          - "kafka.aecid-testbed.local:9092"
        filebeat_output_kafka_topic: "logs"
        filebeat_template: "filebeatkafka.yml.j2"
        filebeat_inputs:
          - type: filestream
            paths:
              - "/var/log/*.log"  # includes auth.log
              - "/var/log/syslog"
        filebeat_modules:
          - tpl: "suricata.yml"
            paths: ["/var/log/suricata/eve.json"]

  tasks:
    - name: Add kafka host entry in /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "192.42.0.254 kafka.aecid-testbed.local"
        state: present
