- name: Install ClientPC
  hosts: all
  become: true
  tasks:
          - name: Allow password login
            ansible.builtin.copy:
              dest: /etc/ssh/sshd_config.d/password.conf
              content: 'PasswordAuthentication yes'
  roles:
          - role: aeciduser
            vars:
                  # pass: aecid
                  aeciduser_pass: "$6$9AqxTPJqYsFXwgPN$xAC4y1Vndk00EaBCuFcJC37BYDYYVAgt9SHymg15KSdKddZnwG.SsQaJvHarH4DYQj3tuboeLa4G5EfL7itcC0"
          - role: aecidtools
            vars:
                  aecidtools_user: "aecid"
          - role: weaklinuxuser
            vars: 
                  weaklinuxuser_user: "judy"
                  weaklinuxuser_pass: "garland"
                  weaklinuxuser_sudo: False
          - role: thunderbird
            vars:
                  thunderbird_user: "judy"
                  populate_emails: true
          - role: mate-desktop
          - role: novnc






