- hosts: inetfw
  roles:
    - kyoushi-gather
  vars:
    kyoushi_gather_ignore_errors: yes
    kyoushi_gather_configs:
      - src: /var/lib/suricata
        recursive: true
      - src: /etc
        recursive: true
        exclude:
          - "/etc/runit "
          - "/etc/sv "
      - src: /var/ossec/etc/ossec.conf

    kyoushi_gather_logs:
      - src: /var/log
        recursive: true


- hosts: reposerver 
  roles:
    - kyoushi-gather
  vars:
    kyoushi_gather_ignore_errors: yes
    kyoushi_gather_logs:
      - /home/john/.bash_history
      - src: /var/log
        recursive: true

    kyoushi_gather_configs:
      - src: /etc
        recursive: true
        exclude:
          - "/etc/runit "
          - "/etc/sv "
      - src: /var/ossec/etc/ossec.conf

- hosts: linuxshare
  roles:
    - kyoushi-gather
  vars:
    kyoushi_gather_ignore_errors: yes
    kyoushi_gather_logs:
      - src: /var/log
        recursive: true

    kyoushi_gather_configs:
      - src: /etc
        recursive: true
        exclude:
          - "/etc/runit "
          - "/etc/sv "
      - src: /var/ossec/etc/ossec.conf


- hosts: attacker
  roles:
    - kyoushi-gather
  vars:
    kyoushi_gather_ignore_errors: yes
    kyoushi_gather_logs:
      - /home/aecid/attackmate.log
      - /home/aecid/output.log
      - /home/aecid/attackmate.json
      - src: /home/aecid/.msf4
        recursive: true
      - src: /var/log
        recursive: true

    kyoushi_gather_configs:
      - src: /home/aecid/scenario*.yml
      - src: /var/www/html
        recursive: true
      - src: /etc
        recursive: true
        exclude:
          - "/etc/runit "
          - "/etc/sv "
          
- hosts: wazuh
  roles:
    - kyoushi-gather
  vars:
    kyoushi_gather_ignore_errors: yes
    kyoushi_gather_logs:
      - src: /var/ossec/logs/alerts
        recursive: true

    kyoushi_gather_configs:
      - src: /etc
        recursive: true
        exclude:
          - "/etc/runit "
          - "/etc/sv "
      - src: /var/ossec/etc/shared
        recursive: true