- name: Install Attacker Host
  hosts: attacker
  become: true
  vars:
    attacker_user: aecid
    attacker_ip: 192.42.1.174
  tasks:
    - name: get user home directory
      ansible.builtin.shell: >
             getent passwd {{ attacker_user }}  | awk -F: '{ print $6 }'
      changed_when: false
      register: user_home
      tags:
        - metasploit
        - zoneminder
        - exploit
        - config
        - install
        - git
        - attackmate
        - playbooks

    - name: Copy playbooks
      become: True
      become_user: "{{attacker_user}}"
      ansible.builtin.template:
          src: "{{ item }}.j2"
          dest: "{{user_home.stdout}}/{{ item }}.yml"
          mode: '0755'
      loop:
          - scenario_3_a_a
      tags:
         - metasploit
         - attackmate
         - exploit
         - config
         - install
         - playbooks

    - name: "Run Scenario 3 a a"
      become: True
      become_user: "{{attacker_user}}"
      ansible.builtin.shell:
          cmd: "/usr/local/bin/attackmate-tmux scenario_3_a_a.yml"
          chdir: "{{user_home.stdout}}"
      tags:
         - scenario_3_a_a
         - metasploit
         - attackmate
         - exploit
