commands:

  - type: browser
    cmd: visit
    url: "http://172.17.100.121:80/zm" 
    creates_session: "cas_session"
    headless: true

  # Type in the username 
  - type: browser
    cmd: type
    text: "admin"
    selector: "input[name='username']"
    session: "cas_session"
    headless: true

  - type: sleep
    seconds: 1

  # Type in the password 
  - type: browser
    cmd: type
    text: "zm_VERY_S3CURE_PASSW0RD"
    selector: "input[name='password']"
    session: "cas_session"
    headless: true

  - type: sleep
    seconds: 1

  # press login button
  - type: browser
    cmd: click
    selector: "button[type='submit']"
    session: "cas_session"
    headless: true
    exit_on_error: false

  - type: sleep
    seconds: 1

  # press apply button
  - type: browser
    cmd: click
    selector: "button[type='submit']"
    session: "cas_session"
    headless: true

  - type: sleep
    seconds: 1

#from here on run in loop
  - type: loop
    cmd: until(3 == 4)
    commands:

      - type: browser
        cmd: click
        selector: "#getConsoleHTML > a"
        session: "cas_session"
        headless: true

      - type: sleep
        seconds: 7

      - type: browser
        cmd: click
        selector: "#getOptionsHTML > a"
        session: "cas_session"
        headless: true

      - type: sleep
        seconds: 7

      - type: browser
        cmd: click
        selector: "#getGroupsHTML > a"
        session: "cas_session"
        headless: true

      - type: sleep
        seconds: 7

     