- hosts: corpdns, inetfw
  roles:
    - kyoushi-gather
  vars:
    kyoushi_gather_ignore_errors: yes
    kyoushi_gather_configs:
      - src: /var/lib/suricata
        recursive: true
      - src: /etc
        recursive: true
        exclude:
          - "/etc/runit "
          - "/etc/sv "
      - src: /var/ossec/etc/ossec.conf

    kyoushi_gather_logs:
      - src: /var/log
        recursive: true

- hosts: attacker
  roles:
    - kyoushi-gather
  vars:
    kyoushi_gather_ignore_errors: yes
    kyoushi_gather_logs:
      - /home/aecid/attackmate.log
      - /home/aecid/output.log
      - /home/aecid/attackmate.json
      - src: /var/log
        recursive: true

    kyoushi_gather_configs:
      - src: /home/aecid/scenario*.yml
      - src: /var/www/html
        recursive: true
      - src: /etc
        recursive: true
        exclude:
          - "/etc/runit "
          - "/etc/sv "

- hosts: client
  roles:
    - kyoushi-gather
  vars:
    kyoushi_gather_ignore_errors: yes
    kyoushi_gather_configs:
      - src: /etc
        recursive: true
        exclude:
          - "/etc/runit "
          - "/etc/sv "
      - src: /var/ossec/etc/ossec.conf

    kyoushi_gather_logs:
      - src: /var/log
        recursive: true

- hosts: videoserver
  roles:
    - kyoushi-gather
  vars:
    kyoushi_gather_ignore_errors: yes
    kyoushi_gather_logs:
      - /var/www/default/log/
      - src: /var/log
        recursive: true

    kyoushi_gather_configs:
      - src: /etc
        recursive: true
        exclude:
          - "/etc/runit "
          - "/etc/sv "
      - src: /var/ossec/etc/ossec.conf
      - src: /var/ossec/ruleset
        recursive: true

- hosts: wazuh
  roles:
    - kyoushi-gather
  vars:
    kyoushi_gather_ignore_errors: yes
    kyoushi_gather_logs:
      - src: /var/ossec/logs/alerts
        recursive: true

    kyoushi_gather_configs:
      - src: /etc
        recursive: true
        exclude:
          - "/etc/runit "
          - "/etc/sv "
      - src: /var/ossec/etc/shared
        recursive: true