- name: Install Attacker Host
  hosts: attacker
  become: true
  vars:
    attacker_user: aecid
  tasks:
    - name: get user home directory
      ansible.builtin.shell: >
             getent passwd {{ attacker_user }}  | awk -F: '{ print $6 }'
      changed_when: false
      register: user_home
      tags:
        - metasploit
        - zoneminder
        - exploit
        - config
        - install
        - git
        - penpal
        - playbook1

    - name: Prepare and Install Metasploit-Exploit
      block:
        - name: Prepare local Metasploit-Path
          ansible.builtin.file:
              path: "{{user_home.stdout}}/.msf4/modules/exploits/unix/webapp"
              state: directory
              recurse: yes
              owner: "{{attacker_user}}"
              group: "{{attacker_user}}"
        
        - name: Upload Zoneminder-Exploit
          ansible.builtin.copy:
              src: zoneminder_snapshots.rb
              dest: "{{user_home.stdout}}/.msf4/modules/exploits/unix/webapp/zoneminder_snapshots.rb"
              owner: "{{attacker_user}}"
              group: "{{attacker_user}}"
              mode: '0644'
      tags:
         - metasploit
         - zoneminder
         - exploit
         - config
         - install

    - name: Prepare and Install PenPal
      block:
        - name: Install Python3-venv
          ansible.builtin.apt:
              name: python3-virtualenv
           #    - name: Git checkout
           #      become: true
           #      become_user: {{ attacker_user }}
           #      ansible.builtin.git:
           #        repo: 'git@github.com:ait-aecid/hackhelfer.git'
           #        dest: "{{user_home.stdout}}/penpal"
           #        accept_hostkey: True
        - name: Install PenPal-Module
          ansible.builtin.pip:
              name: "file://{{user_home.stdout}}/penpal"
              virtualenv: "{{user_home.stdout}}/penpal/venv"
        - name: Copy PenPal-Wrapper
          become: True
          become_user: "{{attacker_user}}"
          ansible.builtin.template:
              src: wrapper.sh.j2
              dest: "{{user_home.stdout}}/penpal/wrapper.sh"
              mode: '0755'
        - name: Copy playbooks
          become: True
          become_user: "{{attacker_user}}"
          ansible.builtin.template:
              src: "{{ item }}.j2"
              dest: "{{user_home.stdout}}/penpal/{{ item }}.yml"
              mode: '0755'
          loop:
              - playbook1
      tags:
         - metasploit
         - penpal
         - exploit
         - config
         - install

    - name: Run Playbook1
      become: True
      become_user: "{{attacker_user}}"
      ansible.builtin.shell:
          cmd: "{{user_home.stdout}}/penpal/wrapper.sh --config=playbook1.yml"
          chdir: "{{user_home.stdout}}/penpal"
      tags:
         - playbook1
         - metasploit
         - penpal
         - exploit

