#cloud-config
system_info:
  default_user:
    name: aecid
    plain_text_passwd: aecid
    lock_passwd: False
bootcmd:
  - echo "nameserver ${dns_server_address}" > /etc/resolv.conf
runcmd:
  -  [echo, "nameserver ${dns_server_address}", >, /etc/resolv.conf]
  -  [apt-get, update]
  -  [apt-get, install, -y, python3]
